config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('rkfabadminvlwlr/', admin.site.urls),
    path('', include('music.urls', namespace="music")),
]

music/urls.py
from django.urls import path
from . import views

app_name = "music"

urlpatterns = [
    path('', views.main, name='main'),
    path('more/', views.more, name='more'),
    path('start/', views.start, name='start'),
    path('question/<str:code>/', views.question, name='question'),
    path('end/<str:code>/', views.end_story, name='end'),
    path('result/<str:code>/', views.calc_result, name='result'),
]

music/models.py
from django.db import models
from django.db.models.fields import TextField
from django.db.models.fields.related import ForeignKey

# Create your models here.


class Mbti(models.Model):
    hash_code = models.CharField(max_length=100, blank=True, null=True)
    order = models.IntegerField(default=1, verbose_name="진행도")
    e_i = models.IntegerField(default=0, verbose_name="E/I")
    s_n = models.IntegerField(default=0, verbose_name="S/N")
    t_f = models.IntegerField(default=0, verbose_name="T/F")
    p_j = models.IntegerField(default=0, verbose_name="P/J")


class Answer(models.Model):
    a_type = models.CharField(max_length=1, verbose_name="답변 유형")
    a_text = models.TextField(verbose_name="답변 텍스트")
    question_n = models.ForeignKey(
        'Question', on_delete=models.SET_NULL, null=True, verbose_name="매칭 질문")

    def __str__(self):
        return self.a_text


class Question(models.Model):
    q_number = models.IntegerField(verbose_name="No.")
    q_title = models.TextField(verbose_name="질문")


class MbtiText(models.Model):
    content = models.TextField(verbose_name="mbti 세부 텍스트")
    result_n = models.ForeignKey(
        'Result', on_delete=models.SET_NULL, null=True, verbose_name="매칭 결과")


class Result(models.Model):
    mbti = models.CharField(max_length=4, verbose_name="mbti 유형")
    song = models.TextField(verbose_name="노래 제목")
    singer = models.TextField(verbose_name="가수")
    close_line = models.TextField(verbose_name="마무리 멘트")
    description = models.TextField(verbose_name="장면 묘사")
    heart = models.TextField(verbose_name="속마음")
    partner = models.OneToOneField(
        'self', on_delete=models.SET_NULL, null=True, blank=True, verbose_name="결이 같은 사람")
    partner_text = models.TextField(null=True, verbose_name="파트너 텍스트")

    def __str__(self):
        return self.mbti

music/views.py
from music.models import Answer, Mbti, Question, Result
import music
from django.shortcuts import get_object_or_404, redirect, render
from random import randint
import hashlib
import time

# Create your views here.
QUESTION_COUNT = 12


def main(request):
    return render(request, 'music/main.html')


def more(request):
    return render(request, 'music/more.html')


def start(request):
    question = get_object_or_404(Question, q_number=1)
    answers = question.answer_set.all()
    this_mbti = Mbti(order=2, e_i=0, s_n=0, t_f=0, p_j=0)
    this_mbti.save()

    temp = str(this_mbti.pk + int(time.time()))
    encoded = temp.encode()
    result = hashlib.sha256(encoded).hexdigest()
    this_mbti.hash_code = result

    this_mbti.save()
    ctx = {
        'question': question,
        'answers': answers,
        'code': this_mbti.hash_code,
        'black': range(0),
        'gray': range(11),
    }
    return render(request, 'music/question.html', context=ctx)


def question(request, code):
    this_mbti = get_object_or_404(Mbti, hash_code=code)

    if this_mbti.order >= 13:
        return redirect('music:end', this_mbti.hash_code)

    question = get_object_or_404(Question, q_number=this_mbti.order)
    answers = question.answer_set.all()

    if request.method == "POST":
        choice = request.POST['choice']
        this_mbti.order += 1

        if choice == 'e':
            this_mbti.e_i += 1
        elif choice == 'i':
            this_mbti.e_i -= 1
        elif choice == 's':
            this_mbti.s_n += 1
        elif choice == 'n':
            this_mbti.s_n -= 1
        elif choice == 't':
            this_mbti.t_f += 1
        elif choice == 'f':
            this_mbti.t_f -= 1
        elif choice == 'p':
            this_mbti.p_j += 1
        elif choice == 'j':
            this_mbti.p_j -= 1
        else:
            print('mbti select error!')

        this_mbti.save()
        print(question)

    qn = question.q_number
    black_circle = qn - 1
    gray_circle = QUESTION_COUNT - black_circle - 1

    ctx = {
        'question': question,
        'answers': answers,
        'code': this_mbti.hash_code,
        'black': range(black_circle),
        'gray': range(gray_circle),
    }

    return render(request, 'music/question.html', context=ctx)


def end_story(request, code):
    return render(request, 'music/endstory.html', {'code': code})


def calc_result(request, code):
    this_mbti = get_object_or_404(Mbti, hash_code=code)

    if this_mbti.order < 13:
        return redirect('music:question', this_mbti.hash_code)

    result = ""
    if this_mbti.e_i > 0:
        result += "e"
    elif this_mbti.e_i == 0:
        x = randint(0, 1)
        if x == 1:
            result += "e"
            this_mbti.e_i += 1
        else:
            result += "i"
            this_mbti.e_i -= 1
    else:
        result += "i"

    if this_mbti.s_n > 0:
        result += "s"
    elif this_mbti.s_n == 0:
        x = randint(0, 1)
        if x == 1:
            result += "s"
            this_mbti.s_n += 1
        else:
            result += "n"
            this_mbti.s_n -= 1
    else:
        result += "n"

    if this_mbti.t_f > 0:
        result += "t"
    elif this_mbti.t_f == 0:
        x = randint(0, 1)
        if x == 1:
            result += "t"
            this_mbti.t_f += 1
        else:
            result += "f"
            this_mbti.t_f -= 1
    else:
        result += "f"

    if this_mbti.p_j > 0:
        result += "p"
    elif this_mbti.p_j == 0:
        x = randint(0, 1)
        if x == 1:
            result += "p"
            this_mbti.p_j += 1
        else:
            result += "j"
            this_mbti.p_j -= 1
    else:
        result += "j"

    this_mbti.save()

    print(result)
    rslt_content = get_object_or_404(Result, mbti=result)
    result_texts = rslt_content.mbtitext_set.all()

    ctx = {
        'result': rslt_content,
        'texts': result_texts,
    }

    return render(request, 'music/result.html', ctx)

templates/music/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Galpi</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.svg' %}">
    <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
    {% block head %}
    {% endblock %}

<body>

    {% block content %}
    {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.6.4/lottie_svg.min.js"></script>
    <script src="/static/js/app.js"></script>
</body>

</html>

templates/music/endstory.html
{% extends "music/base.html" %}
{% load static %}


{% block content %}
<section class="section long">

<div class="end-con">

    <img class="top_logo-q end-logo" src="/static/img/top_logo.svg" alt="top_logo">
    
    <div class="end-text endstory-ani">
        <div class="text-block">
            이제 당신은 죽음의 이유를 당당하게 요구합니다. <br>
            침묵하던 목소리가 말합니다. <br>
        </div>
        <div class="text-block end__gray">
            “당신의 죽음은 노화로 인한 자연사일 수도 있고 불의의 사고일 수도, 어쩌면 지병에 의한 병사일지도 모르죠. 하지만 이제 그 진실에는 아무런 의미가 없어요.” <br>
        </div>
        <div class="text-block">
            약속과 다른 말에 화를 내려는 순간, 목소리가 남은 말을 이어갑니다. <br>
        </div>
        <div class="text-block end__gray">
            “나는 당신에게 삶을 돌려드리려 합니다. 앞으로 당신이 만들어갈 인생이 궁금해졌거든요.” <br>
        </div>
        <div class="text-block">
            그 순간 세상이 환한 빛으로 물듭니다. <br>
        </div>
        <div class="text-block end__gray">
            “오늘의 기억이 당신의 삶을 더 나아지게 만들길 바라요.” <br>
        </div>
        <div class="text-block">
            그 너머에서 마지막으로 들려온 문장은 어쩐지 애정이 듬뿍 담겨 다정하게 느껴집니다. <br>
        </div>
        <div class="text-block end__more">
            다시 눈을 떴을 때, 당신의 앞에는 술렁이는 갈대도, 포근한 오두막도 없습니다. 익숙한 방만이 당신을 반길 뿐이죠. <br>
            <br>
            자, 이제 돌려받은 당신의 삶에 끝에선 어떤 노래가 들려올까요?<br>
        </div>
    </div>
    
    
    <a class="button" href="{% url 'music:result' code=code %}">테스트 결과 보기</a>
</div>
</section>
{% endblock %}

templates/music/main.html
{% extends "music/base.html" %}
{% load static %}

{% block head %}
<meta property="og:title" content="장례식에 흘러나올 내 인생의 주제곡은?" />
<meta property="og:description" content="Galpi : 당신의 삶을 갈피하다" />
<meta property="og:image" content="https://galpi.me/static/img/main_tn.png" />
{% endblock %}

{% block content %}
<section class="section">
<div class="main_section ">
	<img class="top_logo" src="/static/img/top_logo.svg" alt="top_logo">
	
	<img class="main_logo fadedown-ani" src="/static/img/main_logo.svg" alt="main_logo">
	
	<h2 class="main__title1 fadeup-ani">장례식에 흘러나올</h2>
	<h2 class="main__title2 fadeup-ani">내 인생의 주제곡은?</h2>

	<div class="main__hr fadeup-ani"></div>

	<h5 class="main__text fadeup-ani">Galpi.<br>당신의 삶을 갈피하다</h5>
	
	<a class="main__more fadeup-ani" href="{% url 'music:more' %}">더 알아보기 ▶︎</a>
	<button class="main-btn button fadeup-ani " onclick = "location.href = '{% url "music:start" %}' ">시작하기</button>
	<button class="main-btn button fadeup-ani " onclick = "location.href = 'https://tumblbug.com/galpi_me' ">갈피 프로젝트 ▶︎</button>

	<div class="main__copy fadeup-ani">결과 공유하기</div>
	<div class="main_share fadeup-ani">
		<a id="btnLink" class="link-icon twitter" href="#" onclick="clip(); return false;">
			<img src="../../static/img/share/sicon_link.svg" alt="링크">
		</a>
		<a id="btnKakao" class="link-icon kakao" href="javascript:sendLinkCustom();" onclick="sendLinkCustom(); return false;">
			<img src="../../static/img/share/sicon_kakao.svg" id="kakao-link-btn" alt="카카오">
		</a>     
		<a id="btnTwitter" class="link-icon twitter" href="#" onclick="shareTwitter(); return false;">
			<img src="../../static/img/share/sicon_twitter.svg" alt="트위터">
		</a>
		<a id="btnFacebook" class="link-icon facebook" href="#" onclick="shareFacebook(); return false;">
			<img src="../../static/img/share/sicon_facebook.svg" alt="페이스북">
		</a>
		<span>
			<script type="text/javascript" src="https://ssl.pstatic.net/share/js/naver_sharebutton.js"></script>
			<script type="text/javascript">
			new ShareNaver.makeButton({"type": "a" , "title":"갈피 음악테스트"});
			</script>
		</span>
	</div>
</div>
</section>
{% endblock %}

templates/music/more.html
{% extends "music/base.html" %}
{% load static %}

{% block content %}
<section class="section more-sec">

<a class="more__undo sfr-ani" href="{% url 'music:main' %}"><img src="../../static/img/undo.svg" alt="이전으로"></a>

<div class="more-main">
    <div class="more-section">
        <img class="more__logo fadedown-ani" src="../../static/img/more_logo.svg" alt="logo">
        
        <h3 class=" fadedown-ani">당신의 삶을 갈피하다</h3>
    
        <div class="main__hr fadeup-ani"></div>
    
    </div>
    <div class="fadeup-ani">

        <p class="more__text mb-5"><span class="galpi">GALPI</span>는 인생을 갈무리할 수 있는 시간을 갖도록 돕는 프로젝트입니다.</p>
        <p class="more__text mb-5">나만의 <죽음 포트폴리오>를 제작하여 소중한 사람과 나눌 수 있는 서비스를 제공합니다.</p>
        
        <div class="more__part more__part-top more__text">기획 | 배정우,&nbsp; 김경민</div>
        <div class="more__part more__text">개발 | 양정연</div>
        <div class="more__part more__text">디자인 | 최서연</div>
    </div>
</div>


</section>

{% endblock %}

templates/music/question.html
{% extends "music/base.html" %}
{% load static %}

{% block content %}
<section class="section ">

<img class="top_logo-q" src="/static/img/top_logo.svg" alt="top_logo">

<div class="status">
    {% for b in black %}
        <img src="{% static 'img/question/black_circle.svg' %}" alt="">    
    {% endfor %}

    <img src="{% static 'img/question/comma.svg' %}" alt="">    

    {% for g in gray %}
        <img src="{% static 'img/question/gray_circle.svg' %}" alt="">    
    {% endfor %}
</div>

<div class="q_con question-ani">
    <h3 class="q_title">{{ question.q_title|linebreaks }}</h3>
    
    {% for answer in answers %}
        <form action="{% url 'music:question' code=code %}" method="POST">
        {% csrf_token %}
            <button class="button q-btn" name="choice" value="{{ answer.a_type }}">{{ answer.a_text }}</button>
        </form>
    {% endfor %}
    <div class="lottie" id="lottie_{{ question.q_number }}"></div>
    
</div>

</section>
{% endblock %}

templates/music/result.html
{% extends "music/base.html" %}
{% load static %}

{% block head %}
<meta property="og:title" content="장례식에 흘러나올 내 인생의 주제곡은?" />
<meta property="og:description" content="{{result.song}} : {{result.singer}}" />
<meta property="og:image" content="https://galpi.me/static/img/share/result/linkshare_{{ result.pk }}.png" />
{% endblock %}

{% block content %}
<section class="section long sec-padding">
    <div class="res-con fadeup-ani">
        <a href="{% url 'music:main' %}">
            <img class="top_logo-q" src="/static/img/top_logo.svg" alt="top_logo">
        </a>
    
        <h5 class="result_ridi r__title1 ">장례식에 흘러나올</h5>
        <h4 class="result_ridi r__title2 ">내 인생의 주제곡은</h4>
    
        <img class="r__main-img" src="../../static/img/result/Result_Illust-{{ result.pk }}.svg" alt="결과 일러스트">
        
        <h3 class="result_ridi r__title2">{{ result.song|linebreaks }}</h3>
        <h4 class="r__singer ">{{ result.singer }}</h4>
        <img src="../../static/img/result/playlist_another.svg" alt="플레이어 ui">
        
        <div class="r__close">
            <img class="r__close-fac" src="../../static/img/result/quote_left.svg" alt="">
            <h4 class="result_ridi r__close-text">{{ result.close_line|linebreaks }}</h4>
            <img class="r__close-fac" src="../../static/img/result/quote_right.svg" alt="">
        </div>
    
        <h5 class="result_ridi r__desc">{{ result.description|linebreaks }}</h5>
    
    
        <ul class="r__text-ul">
            {% for text in texts %}
                <li class="r__text-li">
                    {{ text.content }}
                </li>
            {% endfor %}
        </ul>
    
        <div class="r__heart">
            <h3 class="result_ridi r__h-title1">인생의 주제곡으로 살펴본</h3>
            <h4 class="result_ridi r__h-title2">당신의 속마음</h4>
            <hr>
            <h5 class="r__h-con">{{ result.heart|linebreaks }}</h5>
        </div>
    
        <div class="r__heart r__partner">
            <h4 class="result_ridi r__h-title2">당신과 영혼의 결이 같은 사람</h4>
            <hr>
            <img src="../../static/img/result/Result_Illust-{{ result.partner.pk }}.svg" alt="파트너 일러스트">
            <h5>{{ result.partner.song }}</h5>
            <h6 class="r__h-singer">{{ result.partner.singer }}</h6>
            <h6 class="r__h-text">{{ result.partner_text|linebreaks }}</h6>
        </div>
    
        <div class="slideshow-container">
            <div class="mySlides fade" onclick="location.href='https://tumblbug.com/galpi_me';">
              <img src="../../static/img/result/banner_1.png" style="width:100%">
            </div>
            
            <div class="mySlides fade" onclick="location.href='https://tumblbug.com/galpi_me';">
              <img src="../../static/img/result/banner_2.png" style="width:100%">
            </div>
            
            <div class="mySlides fade" onclick="location.href='https://tumblbug.com/galpi_me';">
              <img src="../../static/img/result/banner_3.png" style="width:100%">
            </div>
        </div>

        <button class=" r-btn button " onclick = "location.href = 'https://tumblbug.com/galpi_me' ">낯선 목소리 정체 밝히기</button>
        <button class=" r-btn rf-btn button " onclick = "location.href = '{% url "music:main" %}' ">테스트 다시하기</button>

        <div class="main__copy fadeup-ani">결과 공유하기</div>
        <div class="main_share">
            <a id="btnLink" class="link-icon twitter" href="#" onclick="clip(); return false;">
                <img src="../../static/img/share/sicon_link.svg" alt="링크">
            </a>
            <a id="btnKakao" class="link-icon kakao" href="#" onclick="kakaoResultShare('{{ result.song }}', '{{ result.singer }}', '{{ result.pk }}'); return false;">
                <img src="../../static/img/share/sicon_kakao.svg" id="kakao-link-btn" alt="카카오">
            </a>   
            <a id="btnTwitter" class="link-icon twitter" href="#" onclick="shareTwitter(); return false;">
                <img src="../../static/img/share/sicon_twitter.svg" alt="트위터">
            </a>
            <a id="btnFacebook" class="link-icon facebook"  href="#" onclick="shareFacebook(); return false;">
                <img src="../../static/img/share/sicon_facebook.svg" alt="페이스북">
            </a>
            <span>
                <script type="text/javascript" src="https://ssl.pstatic.net/share/js/naver_sharebutton.js"></script>
                <script type="text/javascript">
                new ShareNaver.makeButton({"type": "a" , "title":"갈피 음악테스트"});
                </script>
            </span>
        </div>
    </div>
</section>
{% endblock %}